[pytest]
testpaths = tests

addopts = 
        --browser chromium
        --screenshot only-on-failure
        --tracing retain-on-failure
        --video retain-on-failure
        --html=reports/report.html

markers = 
    smoke : quick sanity check
    regression : full regression suite
